// counter action types
export const INCREASE_COUNTER_BY_AMOUNT = 'INCREASE_COUNTER_BY_AMOUNT';
export const DECREASE_COUNTER_BY_AMOUNT = 'DECREASE_COUNTER_BY_AMOUNT';

export const INCREASE_COUNTER_SUCCESS = 'INCREASE_COUNTER_SUCCESS';
export const DECREASE_COUNTER_SUCCESS = 'DECREASE_COUNTER_SUCCESS';
